# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7cdb1c9996e813b013c209e1f923282981c8091c5fcc918db75729855115c11fc46743147b8ae7f2cc62310d07d43c65fbedb8334e0f41adc28898f0e3554fd

test:
  secret_key_base: 66bccbc4fcbf2a3d5111a2957c7780ef42e67a5973fb0091541630f79c29594158ad8cbb6cd002f14f8a773a174ee3596c30fed63bbcc951c308e5507d1cfea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
